model_list:
  # ----------------------------------------------------------------------
  # A. Atlas Cloud AI - Using the dynamic '*' for multiple models
  # ----------------------------------------------------------------------
  # - model_name: atlas/* # This alias lets clients call any model: "atlas/model-a", "atlas/model-b"
  #   litellm_params:
  #     model: "*" # The underlying provider is LiteLLM's OpenAI-compatible one
  #     api_base: "https://api.atlascloud.ai/v1" 
  #     api_key: "apikey-135efa1e35474e0eb0a6b82619b05353" # Fetched securely from your .env file
  - model_name: atlas/gemini-2.5-pro # This alias lets clients call any model: "atlas/model-a", "atlas/model-b"
    litellm_params:
      model: "gemini-2.5-pro" # The underlying provider is LiteLLM's OpenAI-compatible one
      api_base: "https://api.atlascloud.ai/v1" 
      api_key: "apikey-135efa1e35474e0eb0a6b82619b05353" # Fetched securely from your .env file
      custom_llm_provider: "openai"
  - model_name: atlas/gemini-2.5-flash-lite-preview-09-2025 # This alias lets clients call any model: "atlas/model-a", "atlas/model-b"
    litellm_params:
      model: "gemini-2.5-flash-lite-preview-09-2025" # The underlying provider is LiteLLM's OpenAI-compatible one
      api_base: "https://api.atlascloud.ai/v1" 
      api_key: "apikey-135efa1e35474e0eb0a6b82619b05353" # Fetched securely from your .env file
      custom_llm_provider: "openai"
  - model_name: atlas/Qwen3-235B-A22B-Instruct-2507 # This alias lets clients call any model: "atlas/model-a", "atlas/model-b"
    litellm_params:
      model: "Qwen/Qwen3-235B-A22B-Instruct-2507" # The underlying provider is LiteLLM's OpenAI-compatible one
      api_base: "https://api.atlascloud.ai/v1" 
      api_key: "apikey-135efa1e35474e0eb0a6b82619b05353" # Fetched securely from your .env file
      custom_llm_provider: "openai"
  - model_name: atlas/Qwen3-30B-A3B-Instruct-2507
    litellm_params:
      model: "Qwen/Qwen3-30B-A3B-Instruct-2507" # The underlying provider is LiteLLM's OpenAI-compatible one
      api_base: "https://api.atlascloud.ai/v1" 
      api_key: "apikey-135efa1e35474e0eb0a6b82619b05353" # Fetched securely from your .env file
      custom_llm_provider: "openai"
 
